#include "global.glsl"
#include "raytrace.glsl"

struct vox_matl
{
    uint color;
    uint type;
    float rough;
    float metal;
    float specular;
    float emit;
    float flux;
    float ior;
    float trans;
};

BUFFER(materials_buffer)
{
    vox_matl materials[];
};

BUFFER(uniform_buffer)
{
    mat4 inv_view_proj;
    vec4 position;
};

PUSH_CONSTANT(push_constant)
{
    uniform_buffer ubo;
    materials_buffer mat;
    uvec2 resolution;
    uint frame;
    uint output_image;
    uint voxels_index;
};

vec3 voxel_traversal(ray r)
{
    const uvec3 grid_size = imageSize(image3D_r8[voxels_index]);
    const vec3 grid_min = vec3(0);
    const vec3 grid_max = grid_min + grid_size;
    const vec3 voxels_per_unit = vec3(1);

    float entry_t, exit_t;
    if (!ray_box_intersection(r, grid_min, grid_max, entry_t, exit_t))
    {
        return vec3(0);
    }

    const vec3 entry_pos = ((r.origin + r.dir * (entry_t + EPSILON)) - grid_min) * voxels_per_unit;
    const vec3 stp = sign(r.dir);
    const vec3 delta = abs(r.inv_dir);
    vec3 pos = floor(entry_pos);
    vec3 tmax = (pos - entry_pos + max(stp, 0.0f)) * r.inv_dir;

    uint dir = -1;
    for (int steps = 0;; ++steps)
    {
        const uint voxel = imageLoad(image3D_r8[voxels_index], ivec3(pos)).r;
        if (voxel != 0)
        {
            // normal
            vec3 normal = vec3(0);
            if (dir == -1)
            {
                vec3 a = abs(entry_pos - grid_min);
                vec3 b = abs(entry_pos - grid_max);
                uint ma = min_comp3(a);
                uint mb = min_comp3(b);
                if (a[ma] < b[mb])
                    normal[ma] = -1.0f;
                else
                    normal[mb] = 1.0f;
            }
            else
            {
                normal[dir] = -sign(r.dir[dir]);
            }

            // color
            uint color32 = mat.materials[voxel].color;
            vec3 color = vec3(((color32 >> 0) & 0xff) / 255.0f, ((color32 >> 8) & 0xff) / 255.0f,
                              ((color32 >> 16) & 0xff) / 255.0f);
            if (normal[0] < 0 || normal[1] < 0 || normal[2] < 0)
                color *= 0.5f;
            return color;
        }

        dir = min_comp3(tmax);
        pos[dir] += stp[dir];
        if (pos[dir] < 0.0f || pos[dir] >= grid_size[dir])
            break;
        tmax[dir] += delta[dir];
    }

    return vec3(0);
}

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in;
void main()
{
    uvec2 uv = GOBAL_INVOCATION_ID.xy;

    if (any(greaterThanEqual(uv, resolution)))
    {
        return;
    }

    uint rng = init_rng(uv, frame);

    ray r = ray_gen(uv, resolution, ubo.position, ubo.inv_view_proj, false, rng);

    vec3 color = voxel_traversal(r);
    if (color != vec3(0))
    {
        imageStore(image2D_rgba8[output_image], ivec2(uv), vec4(color, 1));
    }
    else
    {
        imageStore(image2D_rgba8[output_image], ivec2(uv), vec4(vec2(uv) / resolution, 0, 1));
    }
}
