#version 460
#extension GL_EXT_buffer_reference : require
#extension GL_EXT_nonuniform_qualifier : require

layout(std430, buffer_reference, buffer_reference_align = 8) readonly buffer uniform_buffer
{
    mat4 mvp;
};

layout(std430, push_constant) uniform push_constant
{
    uniform_buffer ubo;
    uint render_target_descriptor_index;
};

layout(set = 0, binding = 0) uniform sampler2D tex2D[];
layout(set = 0, binding = 0) uniform sampler3D tex3D[];
layout(set = 0, binding = 0, rgba8) uniform image2D image2D_rgba8[];
layout(set = 0, binding = 0, r8ui) uniform uimage3D image3D_r8[];

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
void main()
{
    imageStore(image2D_rgba8[render_target_descriptor_index], ivec2(gl_GlobalInvocationID.xy), vec4(gl_GlobalInvocationID.x / 1000.0f, gl_GlobalInvocationID.y / 1000.0f, 0, 1));
}
